// <auto-generated />
using System;
using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Management_System.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("System.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("System.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            DateOfBirth = new DateOnly(1903, 6, 25),
                            FullName = "George Orwell",
                            Nationality = "British"
                        },
                        new
                        {
                            AuthorId = 2,
                            DateOfBirth = new DateOnly(1920, 10, 8),
                            FullName = "Frank Herbert",
                            Nationality = "American"
                        },
                        new
                        {
                            AuthorId = 3,
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            FullName = "Fyodor Dostoevsky",
                            Nationality = "Russian"
                        });
                });

            modelBuilder.Entity("System.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            ISBN = "978-0451524935",
                            PublishedYear = 1949,
                            PublisherId = 1,
                            Summary = "A dystopian social science fiction novel and cautionary tale.",
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            CategoryId = 2,
                            ISBN = "978-0451526342",
                            PublishedYear = 1945,
                            PublisherId = 1,
                            Summary = "Allegorical novella using farm animals to critique totalitarianism.",
                            Title = "Animal Farm"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2,
                            CategoryId = 3,
                            ISBN = "978-0441013593",
                            PublishedYear = 1965,
                            PublisherId = 2,
                            Summary = "Epic science fiction saga set on the desert planet Arrakis.",
                            Title = "Dune"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 3,
                            CategoryId = 4,
                            ISBN = "978-0143107637",
                            PublishedYear = 1866,
                            PublisherId = 1,
                            Summary = "Psychological drama exploring morality and redemption.",
                            Title = "Crime and Punishment"
                        });
                });

            modelBuilder.Entity("System.Models.BookItem", b =>
                {
                    b.Property<int>("BookItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookItemId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ConditionNotes")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("BookItemId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("BookId", "BranchId");

                    b.ToTable("BookItems");

                    b.HasData(
                        new
                        {
                            BookItemId = 1,
                            Barcode = "LIB-B001-01",
                            BookId = 1,
                            BranchId = 1,
                            ShelfLocation = "A-12"
                        },
                        new
                        {
                            BookItemId = 2,
                            Barcode = "LIB-B001-02",
                            BookId = 1,
                            BranchId = 1,
                            ShelfLocation = "A-12"
                        },
                        new
                        {
                            BookItemId = 3,
                            Barcode = "LIB-B001-03",
                            BookId = 1,
                            BranchId = 1,
                            ShelfLocation = "A-12"
                        },
                        new
                        {
                            BookItemId = 4,
                            Barcode = "LIB-B001-04",
                            BookId = 1,
                            BranchId = 1,
                            ShelfLocation = "A-12"
                        },
                        new
                        {
                            BookItemId = 5,
                            Barcode = "LIB-B002-01",
                            BookId = 2,
                            BranchId = 1,
                            ShelfLocation = "A-13"
                        },
                        new
                        {
                            BookItemId = 6,
                            Barcode = "LIB-B002-02",
                            BookId = 2,
                            BranchId = 1,
                            ShelfLocation = "A-13"
                        },
                        new
                        {
                            BookItemId = 7,
                            Barcode = "LIB-B002-03",
                            BookId = 2,
                            BranchId = 1,
                            ShelfLocation = "A-13"
                        },
                        new
                        {
                            BookItemId = 8,
                            Barcode = "LIB-B003-01",
                            BookId = 3,
                            BranchId = 1,
                            ShelfLocation = "B-04"
                        },
                        new
                        {
                            BookItemId = 9,
                            Barcode = "LIB-B003-02",
                            BookId = 3,
                            BranchId = 1,
                            ShelfLocation = "B-04"
                        },
                        new
                        {
                            BookItemId = 10,
                            Barcode = "LIB-B004-01",
                            BookId = 4,
                            BranchId = 1,
                            ShelfLocation = "C-01"
                        },
                        new
                        {
                            BookItemId = 11,
                            Barcode = "LIB-B004-02",
                            BookId = 4,
                            BranchId = 1,
                            ShelfLocation = "C-01"
                        });
                });

            modelBuilder.Entity("System.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BorrowRecordId"));

                    b.Property<int>("BookItemId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BorrowDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookItemId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            BorrowRecordId = 1,
                            BookItemId = 1,
                            BorrowDate = new DateOnly(2024, 1, 10),
                            DueDate = new DateOnly(2024, 1, 24),
                            MemberId = 1,
                            ReturnDate = new DateOnly(2024, 1, 24),
                            Status = "Returned"
                        },
                        new
                        {
                            BorrowRecordId = 2,
                            BookItemId = 8,
                            BorrowDate = new DateOnly(2024, 3, 5),
                            DueDate = new DateOnly(2024, 3, 19),
                            MemberId = 1,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BorrowRecordId = 3,
                            BookItemId = 5,
                            BorrowDate = new DateOnly(2024, 2, 20),
                            DueDate = new DateOnly(2024, 3, 5),
                            MemberId = 2,
                            ReturnDate = new DateOnly(2024, 3, 5),
                            Status = "Returned"
                        });
                });

            modelBuilder.Entity("System.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            AddressLine = "1 University Road",
                            Name = "Main Campus Library",
                            Phone = "0300-0000000"
                        },
                        new
                        {
                            BranchId = 2,
                            AddressLine = "22 Market Street",
                            Name = "Downtown Reading Room",
                            Phone = "0300-0000001"
                        });
                });

            modelBuilder.Entity("System.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Society under authoritarian control.",
                            Name = "Dystopian"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Political or social critique.",
                            Name = "Satire"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Speculative futures and worlds.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Enduring literary fiction.",
                            Name = "Classic Literature"
                        });
                });

            modelBuilder.Entity("System.Models.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FineId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BorrowRecordId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("FineId");

                    b.HasIndex("BorrowRecordId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("System.Models.LibrarySettings", b =>
                {
                    b.Property<int>("LibrarySettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LibrarySettingsId"));

                    b.Property<decimal>("DailyFineAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DefaultLoanDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxConcurrentLoansPerMember")
                        .HasColumnType("int");

                    b.HasKey("LibrarySettingsId");

                    b.ToTable("LibrarySettings");

                    b.HasData(
                        new
                        {
                            LibrarySettingsId = 1,
                            DailyFineAmount = 1.50m,
                            DefaultLoanDays = 14,
                            MaxConcurrentLoansPerMember = 5
                        });
                });

            modelBuilder.Entity("System.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("MemberSince")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MemberId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "zara@lib.com",
                            FullName = "Zara Ahmed",
                            IsBlocked = false,
                            MemberSince = new DateOnly(2023, 1, 15),
                            Phone = "0301-1234567"
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "bilal@lib.com",
                            FullName = "Bilal Malik",
                            IsBlocked = false,
                            MemberSince = new DateOnly(2023, 6, 1),
                            Phone = "0312-9876543"
                        });
                });

            modelBuilder.Entity("System.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherId = 1,
                            Country = "United Kingdom",
                            Name = "Secker & Warburg"
                        },
                        new
                        {
                            PublisherId = 2,
                            Country = "United States",
                            Name = "Chilton Books"
                        });
                });

            modelBuilder.Entity("System.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("ReservationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("BookId", "Status");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            BookId = 4,
                            ExpiresOn = new DateOnly(2026, 12, 31),
                            MemberId = 2,
                            ReservedAt = new DateTime(2024, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("System.Models.ApplicationUser", b =>
                {
                    b.HasOne("System.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("System.Models.Book", b =>
                {
                    b.HasOne("System.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("System.Models.BookItem", b =>
                {
                    b.HasOne("System.Models.Book", "Book")
                        .WithMany("Items")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System.Models.Branch", "Branch")
                        .WithMany("Items")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("System.Models.BorrowRecord", b =>
                {
                    b.HasOne("System.Models.BookItem", "BookItem")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System.Models.Member", "Member")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookItem");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("System.Models.Fine", b =>
                {
                    b.HasOne("System.Models.BorrowRecord", "BorrowRecord")
                        .WithMany("Fines")
                        .HasForeignKey("BorrowRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowRecord");
                });

            modelBuilder.Entity("System.Models.Reservation", b =>
                {
                    b.HasOne("System.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("System.Models.Member", "Member")
                        .WithMany("Reservations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("System.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("System.Models.Book", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("System.Models.BookItem", b =>
                {
                    b.Navigation("BorrowRecords");
                });

            modelBuilder.Entity("System.Models.BorrowRecord", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("System.Models.Branch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("System.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("System.Models.Member", b =>
                {
                    b.Navigation("BorrowRecords");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("System.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
